---
- name: Fix Docker installation on Ubuntu
  hosts: elephanto_servers
  gather_facts: yes
  
  tasks:
    - name: Clean up Docker repositories
      shell: |
        rm -f /etc/apt/sources.list.d/docker.list
        rm -f /etc/apt/keyrings/docker.gpg
        apt update
      become: yes

    - name: Install Docker from Ubuntu repos (simpler)
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes
      become: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      become: yes

    - name: Test Docker installation
      shell: docker --version && docker-compose --version
      become: yes